feat: Support usePreinstalledWDA on simulators
appium/appium-xcuitest-driver pull request #2345
Opened 2024-03-21 12:45 UTC by mykola-mokhnach

Related to https://github.com/appium/WebDriverAgent/pull/866

2024-03-21 12:48 UTC, mykola-mokhnach commented
@KazuCocoa Would you have time to test this feature locally?

2024-03-22 04:52 UTC, KazuCocoa approved these changes

2024-03-22 05:31 UTC, KazuCocoa requested changes
mm, wait. seeing a bit weird behavior (just to drop the approval)

2024-03-22 05:42 UTC, KazuCocoa commented on lib/driver.js
> +          this.cachedWdaStatus = this.wda.launch(sessionId);
```suggestion
          this.cachedWdaStatus = await this.wda.launch(sessionId);
```
?

2024-03-22 06:16 UTC, mykola-mokhnach commented on lib/driver.js
> +          this.cachedWdaStatus = this.wda.launch(sessionId);
good catch, thanks

2024-03-22 06:28 UTC, KazuCocoa approved these changes

2024-03-22 07:05 UTC, merged